In [1]:
import pandas as pd
import numpy as ny

In [2]:
hospital_ratings = pd.read_csv("Hospital General Information.csv",encoding="ISO-8859-1")
hospital_ratings

      Provider ID  ... Efficient use of medical imaging national comparison footnote
0           10001  ...                                                NaN
1           10005  ...                                                NaN
2           10006  ...                                                NaN
3           10007  ...  Results are not available for this reporting p...
4           10008  ...  Results are not available for this reporting p...
...           ...  ...                                                ...
4807       670118  ...  Results are not available for this reporting p...
4808       640001  ...  Results are not available for this reporting p...
4809       650001  ...  Results are not available for this reporting p...
4810       650003  ...  Data are shown only for hospitals that partici...
4811       660001  ...  Results are not available for this reporting p...

[4812 rows x 28 columns]

In [3]:
hospital_ratings.isnull()

      Provider ID  ...  Efficient use of medical imaging national comparison footnote
0           False  ...                                               True
1           False  ...                                               True
2           False  ...                                               True
3           False  ...                                              False
4           False  ...                                              False
...           ...  ...                                                ...
4807        False  ...                                              False
4808        False  ...                                              False
4809        False  ...                                              False
4810        False  ...                                              False
4811        False  ...                                              False

[4812 rows x 28 columns]

In [4]:
hospital_ratings.isnull().sum()

Provider ID                                                         0
Hospital Name                                                       0
Address                                                             0
City                                                                0
State                                                               0
ZIP Code                                                            0
County Name                                                        15
Phone Number                                                        0
Hospital Type                                                       0
Hospital Ownership                                                  0
Emergency Services                                                  0
Meets criteria for meaningful use of EHRs                         143
Hospital overall rating                                             0
Hospital overall rating footnote                                 3414
Mortality national comparison                                       0
Mortality national comparison footnote                           3460
Safety of care national comparison                                  0
Safety of care national comparison footnote                      2644
Readmission national comparison                                     0
Readmission national comparison footnote                         3795
Patient experience national comparison                              0
Patient experience national comparison footnote                  3443
Effectiveness of care national comparison                           0
Effectiveness of care national comparison footnote               3610
Timeliness of care national comparison                              0
Timeliness of care national comparison footnote                  3546
Efficient use of medical imaging national comparison                0
Efficient use of medical imaging national comparison footnote    2779
dtype: int64

In [5]:
hospital_ratings.notnull()

      Provider ID  ...  Efficient use of medical imaging national comparison footnote
0            True  ...                                              False
1            True  ...                                              False
2            True  ...                                              False
3            True  ...                                               True
4            True  ...                                               True
...           ...  ...                                                ...
4807         True  ...                                               True
4808         True  ...                                               True
4809         True  ...                                               True
4810         True  ...                                               True
4811         True  ...                                               True

[4812 rows x 28 columns]

In [6]:
dff=hospital_ratings.groupby(['Hospital Ownership','Hospital Type']).size()
dff

Hospital Ownership                           Hospital Type
Government - Federal                         Acute Care Hospitals           37
                                             Critical Access Hospitals       8
Government - Hospital District or Authority  Acute Care Hospitals          273
                                             Childrens                       1
                                             Critical Access Hospitals     287
Government - Local                           Acute Care Hospitals          176
                                             Critical Access Hospitals     231
Government - State                           Acute Care Hospitals           50
                                             Childrens                       3
                                             Critical Access Hospitals      12
Physician                                    Acute Care Hospitals           65
                                             Critical Access Hospitals       3
Proprietary                                  Acute Care Hospitals          725
                                             Childrens                       8
                                             Critical Access Hospitals      67
Tribal                                       Acute Care Hospitals            5
                                             Critical Access Hospitals       4
Voluntary non-profit - Church                Acute Care Hospitals          278
                                             Childrens                       1
                                             Critical Access Hospitals      64
Voluntary non-profit - Other                 Acute Care Hospitals          359
                                             Childrens                      16
                                             Critical Access Hospitals      87
Voluntary non-profit - Private               Acute Care Hospitals         1401
                                             Childrens                      70
                                             Critical Access Hospitals     581
dtype: int64

In [7]:
df2=hospital_ratings.groupby(['State']).size()
df2

State
AK     22
AL     90
AR     75
AS      1
AZ     80
CA    343
CO     78
CT     31
DC      8
DE      7
FL    187
GA    133
GU      2
HI     23
IA    116
ID     41
IL    180
IN    120
KS    137
KY     94
LA    121
MA     64
MD     49
ME     33
MI    131
MN    131
MO    112
MP      1
MS     95
MT     62
NC    107
ND     44
NE     89
NH     26
NJ     66
NM     41
NV     35
NY    171
OH    168
OK    124
OR     60
PA    171
PR     52
RI     11
SC     60
SD     60
TN    107
TX    411
UT     46
VA     86
VI      2
VT     14
WA     91
WI    126
WV     49
WY     28
dtype: int64

In [8]:
df3=hospital_ratings[hospital_ratings['State']=='TX']
df3

      Provider ID  ... Efficient use of medical imaging national comparison footnote
3954       450002  ...                                                NaN
3955       450007  ...                                                NaN
3956       450010  ...                                                NaN
3957       450011  ...                                                NaN
3958       450015  ...                                                NaN
...           ...  ...                                                ...
4803       670114  ...  Results are not available for this reporting p...
4804       670115  ...  Data are shown only for hospitals that partici...
4805       670116  ...  Results are not available for this reporting p...
4806       670117  ...  Results are not available for this reporting p...
4807       670118  ...  Results are not available for this reporting p...

[411 rows x 28 columns]

In [9]:
distri=hospital_ratings[['State','Hospital Ownership','Hospital Type']]
distri

     State                           Hospital Ownership         Hospital Type
0       AL  Government - Hospital District or Authority  Acute Care Hospitals
1       AL  Government - Hospital District or Authority  Acute Care Hospitals
2       AL  Government - Hospital District or Authority  Acute Care Hospitals
3       AL               Voluntary non-profit - Private  Acute Care Hospitals
4       AL                                  Proprietary  Acute Care Hospitals
...    ...                                          ...                   ...
4807    TX                                  Proprietary  Acute Care Hospitals
4808    AS  Government - Hospital District or Authority  Acute Care Hospitals
4809    GU                           Government - Local  Acute Care Hospitals
4810    GU               Voluntary non-profit - Private  Acute Care Hospitals
4811    MP                                  Proprietary  Acute Care Hospitals

[4812 rows x 3 columns]

In [10]:
distri1 = distri[hospital_ratings['State']=='TX']
distri1

     State                           Hospital Ownership         Hospital Type
3954    TX                                  Proprietary  Acute Care Hospitals
3955    TX               Voluntary non-profit - Private  Acute Care Hospitals
3956    TX               Voluntary non-profit - Private  Acute Care Hospitals
3957    TX               Voluntary non-profit - Private  Acute Care Hospitals
3958    TX  Government - Hospital District or Authority  Acute Care Hospitals
...    ...                                          ...                   ...
4803    TX                                  Proprietary  Acute Care Hospitals
4804    TX                                  Proprietary  Acute Care Hospitals
4805    TX  Government - Hospital District or Authority  Acute Care Hospitals
4806    TX                                  Proprietary  Acute Care Hospitals
4807    TX                                  Proprietary  Acute Care Hospitals

[411 rows x 3 columns]

In [11]:
time=pd.crosstab(hospital_ratings['Hospital Name'],hospital_ratings['Timeliness of care national comparison footnote']=='Above the national average')
time

Timeliness of care national comparison footnote  False
Hospital Name
ABBEVILLE AREA MEDICAL CENTER                        1
ABBEVILLE GENERAL HOSPITAL                           1
ABBOTT NORTHWESTERN HOSPITAL                         1
ABILENE REGIONAL MEDICAL CENTER                      1
ABINGTON MEMORIAL HOSPITAL                           1
...                                                ...
YORK HOSPITAL                                        2
YUKON KUSKOKWIM DELTA REG HOSPITAL                   1
YUMA DISTRICT HOSPITAL                               1
YUMA REGIONAL MEDICAL CENTER                         1
ZUNI COMPREHENSIVE COMMUNITY HEALTH CENTER           1

[4623 rows x 1 columns]

In [12]:
ratings=hospital_ratings[['Hospital Name','Hospital overall rating']]
ratings

                         Hospital Name Hospital overall rating
0     SOUTHEAST ALABAMA MEDICAL CENTER                       3
1        MARSHALL MEDICAL CENTER SOUTH                       3
2       ELIZA COFFEE MEMORIAL HOSPITAL                       2
3             MIZELL MEMORIAL HOSPITAL                       2
4          CRENSHAW COMMUNITY HOSPITAL                       3
...                                ...                     ...
4807              FIRST TEXAS HOSPITAL           Not Available
4808       LBJ TROPICAL MEDICAL CENTER           Not Available
4809  GUAM MEMORIAL HOSPITAL AUTHORITY                       3
4810        GUAM REGIONAL MEDICAL CITY           Not Available
4811        COMMONWEALTH HEALTH CENTER           Not Available

[4812 rows x 2 columns]

In [13]:
Acute=hospital_ratings.loc[(hospital_ratings["Hospital Type"]=="Acute Care Hospitals")&(hospital_ratings["Hospital overall rating"]=="4"),["State"]]
Acute

     State
10      AL
11      AL
14      AL
15      AL
17      AL
...    ...
4777    TX
4779    TX
4780    TX
4782    TX
4784    TX

[724 rows x 1 columns]